<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @category   MSP
 * @package    MSP_ReCaptcha
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block MSP\ReCaptcha\Block\Frontend\ReCaptcha */
?>
<div class="field-recaptcha" id="msp-recaptcha-container-mini" data-bind="scope:'msp-recaptcha-mini'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<?php
    $jsLayout = $block->getJsLayout();
    $jsLayout = json_decode($jsLayout, true);
    if(empty($jsLayout['components']['msp-recaptcha'])){
    	$jsLayout['components']['msp-recaptcha'] = $jsLayout['components'][$this->getRecaptchaId()];
    }
    $jsLayout['components']['msp-recaptcha-mini'] = $jsLayout['components']['msp-recaptcha'];
    unset($jsLayout['components']['msp-recaptcha']);
    $jsLayout = json_encode($jsLayout);
?>
<script type="text/x-magento-init">
{
    "#msp-recaptcha-container-mini": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $jsLayout;?>
    }
}
</script>
