<?php
/**
* Copyright © 2018 Codazon. All rights reserved.
* See COPYING.txt for license details.
*/

?>

<?php
$helper = $this->getHelper();
$config = $this->getMenuConfig();
$this->addData($config);
$html = $this->getHtml();
$widget = ['Codazon_Lookbookpro/js/category-menu' => []];
?>
<?php if ($html) : ?>
<div class="block block-lookbook-category-menu" data-role="lookbook-category-menu">
    <div class="block-title">
        <strong role="heading"><?= __('Lookbook Categories') ?></strong>
    </div>
    <div class="block-content"><ul class="lookbook-category-menu toggle-menu" data-mage-init='<?php echo json_encode($widget) ?>'><?= $html ?></ul></div>
</div>
<?php endif ?>