<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
	$_themeHelper = $this->helper('Codazon\ThemeOptions\Helper\Data');
	$_isShowPopup = $_themeHelper->getConfig('general_section/newsletter_popup/enable');
?>
<?php if($_isShowPopup == 1): ?>
<div class="cdz-popup-content" style="display:none">
<!-- popup-cotent -->
    <?php echo $block->getChildHtml('block.popup.container') ?>
</div>
<script>
require([
        'jquery',
        'mage/cookies',
        'modal',
        'domReady!'
],function($){
    $.fn.addBack = function (selector) {
    return this.add(selector == null ? this.prevObject : this.prevObject.filter(selector));
}
   	if(!$.mage.cookies.get("fastest-popup")){
        $.mage.cookies.set('fastest-popup', 'true');
        var $newsletterPopup = $('.cdz-popup-content').first();
        $newsletterPopup.modal({
            autoOpen: true,
            modalClass: "cdz-newsletter-popup"
        });
        $newsletterPopup.parents('.cdz-newsletter-popup').first().wrap('<div class="modals-wrapper cdz-popup-wrapper">')
  	}
});
</script>
<?php endif ?>
