<?php
    use Magento\Framework\App\Action\Action;
    ?>
<?php
    $_productCollection = $block->getProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $uniqId = uniqid('block_');
?>
<?php if (!$_productCollection->count()): ?>
<div class="message info empty">
    <div><?php echo __('We can\'t find products matching the selection.') ?></div>
</div>
<?php else: ?>
<?php echo $block->getAdditionalHtml() ?>
<?php
    $viewMode = 'slider';
    $image = 'category_page_grid';
    $image_hover = 'category_page_grid_hover';
    $title = $block->getTitle();
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $pos = $block->getPositioned();
    $sliderItem = $block->getData('slider_item') ? $block->getData('slider_item') : 4;
    $swatchesRender = $block->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setTemplate('Codazon_ProductFilter::swatches/renderer.phtml');
    $gallery = $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Codazon_ProductFilter::product/gallery.phtml')
        ->setImageWidth($block->getData('thumb_width'))->setImageHeight($block->getData('thumb_height'));
    $labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');
    $qsHelper = $this->helper('Codazon\QuickShop\Helper\Data');
    $filterHelper = $this->helper('Codazon\ProductFilter\Helper\Data');
    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
?>
<div class="block widget block-products-list grid_slider <?php echo $viewMode; ?>"  id="<?php echo $uniqId ?>">
    <?php if ($title):?>
    <div class="cdz-block-title">
        <h2 class="b-title"><span><?php echo $title; ?></span></h2>
    </div>
    <?php endif ?>
    <div class="block-content">
        <div class="products gallery-grid products-grid wrapper same-height <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>"> 
            <?php $iterator = 1; ?>
            <div class="products list items product-items <?php echo $block->getData('show_slider') ? 'cdz-slider' : '' ?>"
                <?php if($block->getData('show_slider')) : ?>
                <?php $slider_item =  ($block->getData('slider_item')) ?  $block->getData('slider_item') : 6 ?>
                data-items="<?php echo $slider_item ?>"
                data-items-0="2"
                data-items-480="2"
                data-items-768="<?php echo abs($slider_item - 3) ?>"                      
                data-items-1024="<?php echo abs($slider_item - 2) ?>" 
                data-items-1280="<?php echo abs($slider_item - 1) ?>"
                data-items-1440="<?php echo $slider_item ?>"
                data-loop="false"
                data-margin="10"
                data-autoWidth="false"
                <?php endif; ?>
                >
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                <?php echo($iterator++ == 1) ? '<div class="item product product-item cdz-transparent">' : '</div><div class="item product product-item cdz-transparent">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <div class="cdz-hover-section">
                        <div class="cdz-product-top">
                            <?php
                                $productImage = $block->getImage($_product, $image);
                                $productHoverImage = $block->getImage($_product, $image_hover);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>
                            <?php if($block->isShow('thumb')): ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <span class="main-image">
                            <?php echo $productImage->toHtml(); ?>
                            </span>
                            </a>
                            <?php endif ?>
                            <div class="addto-hover-container">
                                <div class="addto-button">
                                    <?php echo $qsHelper->getQuickShopButton($_product) ?>
                                </div>
                            </div>
                            <?php $labelHelper->showLabel($_product) ?>
                        </div>
                    </div>
                    <div class="product details product-item-details">
                        <?php echo $gallery->setProduct($_product)->toHtml(); ?>
                        <div class="info-details">
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <?php if($block->isShow('name')): ?>
                            <strong class="product name product-item-name">
                            <a class="product-item-link"
                                href="<?php echo $_product->getProductUrl() ?>">
                            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                            </strong>
                            <?php endif ?>
                            <?php if($block->isShow('review')): ?>
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <?php endif ?>
                            <?php if($block->isShow('price')): ?>
                            <?php echo $block->getProductPrice($_product) ?>
                            <?php endif ?>
                            <?php echo $swatchesRender->setProduct($_product)->toHtml() ?>
                            <?php echo $block->getProductDetailsHtml($_product); ?>
                            <?php if($block->isShow('description')): ?>
                            <div class="product description product-item-description">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"
                                    class="action more"><?php echo __('Learn More') ?></a>
                            </div>
                            <?php endif; ?>
                        </div>
                        <div class="product-item-inner cdz-buttons-container">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <?php if($block->isShow('addtocart')): ?>
                                <div class="actions-primary" <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php  echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php  echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php  echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php  echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <?php if ($filterHelper->shouldRenderQuantity($_product)): ?>
                                            <div class="field qty box-tocart">                                         
                                                <div class="control">
                                                    <div class="qty-minus"> <a class="btn-qty minus" href="javascript:void(0)">-</a></div>
                                                    <div class="qty-input">
                                                        <input type="number"
                                                            name="qty"
                                                            id="<?php echo $_product->getId() ?>_qty"
                                                            maxlength="12"
                                                            value="<?php  echo $filterHelper->getProductDefaultQty($_product) * 1 ?>"
                                                            title="<?php  echo __('Qty') ?>" class="input-text qty"
                                                            data-validate="<?php echo $block->escapeHtml(json_encode($filterHelper->getQuantityValidators())) ?>"
                                                        />
                                                    </div>
                                                    <div class="qty-plus"> <a class="btn-qty plus" href="javascript:void(0)">+</a></div>
                                                </div>
                                            </div>
                                            <?php endif; ?>
                                            <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                            class="action tocart primary show-tooltip"><span><?php  echo __('Add to Cart') ?></span></button>
                                        </form>
                                    <?php else: ?>
                                    <?php if ($_product->getIsSalable()): ?>
                                    <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                    <?php else: ?>
                                    <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php endif ?>
                                
                                <div class="product-actions-right">
                                    <?php if($block->isShow('addto')): ?>
                                    <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
				                            <a href="#"
				                               class="action tocompare"
				                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				                               data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
				                               role="button">
				                                <span><?php echo __('Add to Compare') ?></span>
				                            </a>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
				                                <a href="#"
				                                   class="action towishlist"
				                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
				                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
				                                   data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
				                                   data-action="add-to-wishlist"
				                                   role="button">
				                                    <span><?php echo __('Add to Wish List') ?></span>
				                                </a>
				                            <?php endif; ?>
				                        </div>
                                    <?php endif ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "#<?php echo $uniqId ?> [data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery','Magento_Theme/js/fastest_fashion'],function($){
        var $_productWrap = $("#<?php echo $uniqId ?>");
        $_productWrap.initFilter();
    });
</script>