<?php
$postCount = $block->getData('post_count')?$block->getData('post_count'):5;
$posts = $block->getPostCollection()->setPageSize($postCount,1);
$showSlider = $block->getShowSlider();
$initHeight = $block->getData('thumb_height');
$initWidth = $block->getData('thumb_width');
$uniqId = uniqid('blog_');
$helper = $this->helper('Magefan\Blog\Helper\Image');
?>

<?php if( count($posts) > 0 ): ?>
<div class="cdz_wapper-blog" id="<?php echo $uniqId ?>">
    <?php $i = 0 ?>
    <div class="post-items same-height owl-carousel" data-noslider="true">
    <?php $i=0;$j=1; foreach($posts as $item): ?>
    <?php
        if($j > 5) $j = 1;
        if( ($i%5) == 0){
            $descLength = 150;
            $class = 'width-1'; 
            $width = $initWidth*2;
            $height = $initHeight*2;
        }else{
            $descLength = 150;
            $class = 'width-2'; 
            $width = $initWidth;
            $height = $initHeight;
        }
        $url = $item->getPostUrl();
        $desc = $item->getMetaDescription();
        if(strlen($desc)> $descLength ) { 
            $strCutDesc = substr($desc, 0, $descLength);
            $desc = substr($strCutDesc, 0, strrpos($strCutDesc, ' ')).'&hellip;';
        }
        $desc = $this->stripTags($desc,null,true);
    ?>
        <div class="post-item <?php echo $class ?> item-<?php echo $j ?>">
            <div class="cdz-blog-top">
                <a href="<?php echo $url ?>">                
                    <img class="img-responsive" width="<?php echo $width ?>" height="<?php echo $height ?>" src="<?php echo $helper->init($item->getPostImage())->resize($width,$height); ?>" />
                </a>
                
            </div>
            <div class="cdz-blog-bottom">
                <h5 class="blog-title"><a href="<?php echo $url ?>"><?php echo $item->getTitle() ?></a></h5>
                <div class="blog-desc"><?php echo $desc ?></div>
                <div class="blog-date"><?php echo $block->getPostedOn($item,'F d, Y'); ?></span></div>
                <div class="blog-text-link"><div class="text-link-center"><a class="btn-link" href="<?php echo $url ?>"><span><?php echo __('Read more') ?></span></a></div></div>
                
            </div>
        </div>
    <?php $i++;$j++; endforeach ?>
    </div>
</div>
<?php endif ?>
<script>
require(['jquery','cdz_slider','Magento_Theme/js/fastest_fashion'],function($){
    var $blog = $('#<?php echo $uniqId ?>');
    $blog.find('.post-items').owlCarousel({
        margin: 20,
        nav: true,
        dots: false,
        rtl: (ThemeOptions.rtl_layout == 1 ? true : false),
        items: 5,
        responsiveClass: true,
        responsive:{
            0: {items: 1},
            480: {items: 2},
            768: {items: 3},
            1024: {items: 4},
            1280: {items: 4},
            1440: {items: 5},
        },
        onInitialized: function(){
            $blog.sameHeightItems({
                sItem: '.cdz-blog-bottom'
            });
        },
        onResized: function(){
            $blog.trigger('layoutUpdated');
        }
    });
})
</script>