<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php
    $_themeHelper = $this->helper('Codazon\ThemeOptions\Helper\Data');
    $_mobileHelper = $this->helper('Codazon\ThemeOptions\Helper\Mobile');
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
        <img class="main-logo" src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
        <?php 
            $mobileLogo = $_themeHelper->getMediaUrl() .'codazon/themeoptions/background/'.$_themeHelper->getConfig('general_section/header/mobile_logo'); 
            $mobileLogo = (strlen($_themeHelper->getConfig('general_section/header/mobile_logo')) > 3) ? $mobileLogo : $block->getLogoSrc();
        ?>
        <img class="small-logo" src="<?php echo $mobileLogo ?>"
             alt="<?php echo $block->getLogoAlt() ?>"
             <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />      
    </a>
<?php if($mobileLogo == $block->getLogoSrc()): ?>
<script type="text/javascript">
require(['jquery'],function($){      
      var logoSrc = "<?php echo $block->getLogoSrc() ?>";
      var imageType = logoSrc.substr(-4);
    var imageName = logoSrc.substr(0, logoSrc.length - 4);
    imageName += "-small" + imageType;
    $('.small-logo').attr('src',imageName);
});
</script>
<?php endif ?>
