<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<?php $parent = $block->getParentBlock(); ?>
<div class="login-section">
    <?php if( $parent->isLoggedIn() ): ?>
    <?php $dataPostParam = sprintf(" data-post='%s'", $parent->getPostParams()); ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action login primary" <?php echo $parent->getLinkAttributes(); ?> <?php echo $dataPostParam; ?>><span><?php echo __('Log out') ?></span></a>
        </div>
    </div>
    <?php else : ?>
    <?php
        $modal = [
            'title' => __('Login information'),
            'modalClass' => 'login-modal-wrap confirm',
            'responsive' => true,
            'trigger' => '[data-role="cdz-login-trigger"]',
            'buttons' => []
        ];
    ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button class="action login primary" data-role="cdz-login-trigger"><span><?php echo __('Login') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action remind" href="<?php echo $block->getForgotPasswordUrl() ?>"><span><?php echo __('Forgot Your Password?') ?></span></a>
        </div>
    </div>
    <div class="login-modal" style="display:none;" id="cdz-login-modal">
        <div class="block block-customer-login">
            <div class="block-content" >
                <form class="form form-login"
                      action="<?php echo $block->getPostActionUrl() ?>"
                      method="post"
                      id="login-form-mini"
                      data-mage-init='{"validation":{}}'>
                    <?php echo $block->getBlockHtml('formkey'); ?>
                    <fieldset class="fieldset login" data-hasrequired="<?php echo __('* Required Fields') ?>">
                        <div class="field email required">
                            <div class="control">
                                <input placeholder="<?php echo __('Email') ?>" name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password required">
                            <div class="control">
                                <input placeholder="<?php echo __('Password') ?>" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}">
                            </div>
                        </div>
                        <?php echo $block->getChildHtml('form_additional_info'); ?>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action login primary" name="send" id="send2"><span><?php echo __('Login') ?></span></button>
                            </div>
                            <div class="secondary">
                                <a class="action remind" href="<?php echo $block->getForgotPasswordUrl() ?>"><span><?php echo __('Forgot Your Password?') ?></span></a>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript">
    require(['jquery','Magento_Ui/js/modal/modal'],function($){
        var $loginModal = $('#cdz-login-modal');
        $loginModal.modal(<?php echo json_encode($modal) ?>);
    });
    </script>
    <?php endif ?>
</div>