<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<?php
	$_optionHelper = $this->helper('Codazon\ThemeOptions\Helper\Data');			 
	$width = $_optionHelper->getConfig('general_section/product_view/base_image_width') ?: $block->getImageAttribute('product_page_image_medium', 'width'); 	 
	$height = $_optionHelper->getConfig('general_section/product_view/base_image_height') ?: $block->getImageAttribute('product_page_image_medium', 'height');	
	$thumbWidth = 	$_optionHelper->getConfig('general_section/product_view/moreview_image_width') ?: $block->getImageAttribute('product_page_image_small', 'width');	
	$thumbHeight = 	$_optionHelper->getConfig('general_section/product_view/moreview_image_height') ?: $block->getImageAttribute('product_page_image_small', 'height');
	$fullViewType = $_optionHelper->getConfig('general_section/product_view/full_view_type');
	$allowFullScreen = is_null($fullViewType)?$block->getVar("gallery/allowfullscreen"):(($fullViewType!='pop_up')?'true':'false');
	$productLensZoom = $_optionHelper->getConfig('general_section/product_view/product_lens_zoom');
    $labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');
?>
<script type="text/javascript">
	<?php $requireJs = ($fullViewType == 'popup')?"'jquery','Magento_Catalog/js/cdzZoom','Magento_Ui/js/modal/modal','js/jquery.nicescroll.min'":"'jquery','Magento_Catalog/js/cdzZoom','Magento_Ui/js/modal/modal'"; ?>
	
	require([<?php echo $requireJs ?>],function ($) {
		var imgModal = false, $imgBox = false;
		var widthImage = <?php /* @escapeNotVerified */ echo $width; ?>;
		$("[data-gallery-role=gallery-placeholder]").on("gallery:loaded",function () {
			
			var widthColumn = $('.columns').width();
			var percentWidthImage = widthImage/widthColumn * 100;
			var percentWidthInfo = 100 - percentWidthImage - 3;
			if(percentWidthImage < 61)	
			{
				$('.product.media').css('width',percentWidthImage+'%');
				$('.product-info-main').css('width',percentWidthInfo+'%');
			}
			<?php if($fullViewType == 'pop_up'): ?>
			if( $('#cdz-img-box').length == 0 ){
				var $this = $(this);
				var $wrap = $('.fotorama__wrap',$this);
				var $viewFullBtn = $('<a class="full-view" href="javascript:void(0)">Full</a>');
				$imgBox = $('<div class="cdz-img-box" id="cdz-img-box"><div class="img-box-inner"><img class="full-img" src="" /></div></div>');
				$viewFullBtn.appendTo($('.fotorama__stage',$wrap));
				$imgBox.hide().appendTo('body');
				imgModal = $imgBox.modal({
					wrapperClass: 'product-image-box',
					buttons: [],
					innerScroll: true,
					modalVisibleClass: '_show',
					opened: function(){
						$('#cdz-img-box').parents('.modal-content').first().niceScroll({cursorcolor:'#999999', cursorborder:'#747070'});
					}
				});
				$viewFullBtn.on('click',function(e){
					e.preventDefault();
                    var bg = $('.fotorama__active .magnify').css('background-image');
                    bg = bg.replace('url(','').replace(')','').replace(/\"/gi, "");
					$('.full-img',$imgBox).attr('src',bg);
					imgModal.modal('openModal');
				});
			}
			<?php endif ?>
		});
		<?php if($productLensZoom == '1'): ?>
		$("[data-gallery-role=gallery-placeholder]").on("fotorama:showend fotorama:load",function () {
			var $this = $(this);
			var $stage = $('.fotorama__stage',$this);
			$('.fotorama__stage__frame',$stage).not('.fotorama-video-container').each(function(i,e){
				var $frame = $(this);
				$frame.cdzZoom();
				if(imgModal){
					$('.magnify',$this).on('click',function(e){
						e.preventDefault();
						$('.full-img',$imgBox).attr('src',$('.fotorama__active').attr('href'));
						imgModal.modal('openModal');
					});
				}
			});
		});
		<?php endif ?>
	})
</script>
<?php $labelHelper->showLabel($this->getProduct()) ?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask">
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...') ?>">
        </div>
    </div>
</div>
<!--Fix for jumping content. Loader must be the same size as gallery.-->
<script>
    var config = {
            "width": <?php /* @escapeNotVerified */ echo $width; ?>,
            "thumbheight": <?php /* @escapeNotVerified */ echo $thumbHeight ?: $thumbWidth; ?>,
            "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
            "height": <?php /* @escapeNotVerified */ echo $height; ?>
        },
        thumbBarHeight = 0,
        loader = document.querySelectorAll('[data-gallery-role="gallery-placeholder"] [data-role="loader"]')[0];

    if (config.navtype === 'horizontal') {
        thumbBarHeight = config.thumbheight;
    }    
	
    loader.style.paddingBottom = ( config.height / config.width * 100) + "%";
</script>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?php /* @escapeNotVerified */ echo $block->getMagnifier(); ?>,
                "data": <?php /* @escapeNotVerified */ echo $block->getGalleryImagesJson(); ?>,
                "options": {
                    <?php if(count(json_decode($block->getGalleryImagesJson(),true)) > 1): ?>
                    	"nav": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/nav"); ?>",
                    <?php else: ?>
                        "nav": false,
                    <?php endif; ?>
                    "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/loop") ? 'true' : 'false' ?>,
                    "keyboard": <?= /* @escapeNotVerified */ $block->getVar("gallery/keyboard") ? 'true' : 'false' ?>,
                    "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/arrows") ? 'true' : 'false' ?>,
                    "allowfullscreen": <?= /* @escapeNotVerified */ $block->getVar("gallery/allowfullscreen") ? 'true' : 'false' ?>,
                    "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/caption") ? 'true' : 'false' ?>,
                    "width": <?php /* @escapeNotVerified */ echo $width; ?>,
                    "thumbwidth": <?php /* @escapeNotVerified */ echo $thumbWidth; ?>,
                    "thumbheight": <?php /* @escapeNotVerified */ echo $thumbHeight
                        ?: $thumbWidth; ?>,
                    "height": <?php /* @escapeNotVerified */ echo $height
                        ?: $width ?>,
                    <?php if ($block->getVar("gallery/transition/duration")): ?>
                        "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/duration"); ?>,
                    <?php endif; ?>
                    "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/effect"); ?>",
                    <?php if (($block->getVar("gallery/navarrows"))): ?>
                        "navarrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/navarrows"); ?>,
                    <?php endif; ?>
                    "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
                    "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navdir"); ?>",
                    "direction": "<?php /* @escapeNotVerified */  echo $_optionHelper->getConfig("general_section/layout/enable_rtl") ? 'rtl' : 'ltr'; ?>"
                },
                "fullscreen": {
                    "nav": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/nav") ?>",
                    "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/loop") ? 'true' : 'false' ?>,
                    "navdir": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navdir") ?>",
                    "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navarrows") ? 'true' : 'false' ?>,
                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navtype") ?>",
                    "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/arrows") ? 'true' : 'false' ?>,
                    "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/caption") ? 'true' : 'false' ?>,
                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/duration") ?>,
                        <?php endif; ?>
                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/effect") ?>"
                },
                "breakpoints": <?php /* @escapeNotVerified */ echo $block->getBreakpoints(); ?>
            }
        }
    }
</script>

