<?php
use Magento\Framework\App\Action\Action;
?>

<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$uniqId = uniqid('block_');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
	$descLength = 100;
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $image_hover = 'category_page_grid_hover';
    $showDescription = false;
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $classid = md5(json_encode($block->getData()));
	$labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
	$swatchesRender = $block->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setTemplate('Codazon_ProductFilter::swatches/renderer_style01.phtml');
    ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $viewMode; ?>" id="<?php echo $uniqId ?>">
		<?php if ($title):?>
		<div class="cdz-block-title">
		    <h2 class="b-title"><span><?php /* @escapeNotVerified */ echo $title; ?></span></h2>
		</div>
		<?php endif ?>
		<div class="block-content same-height">
			<div class="products products-grid wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
				<?php $iterator = 1; ?>
				<div class="products list items product-items">
				    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				    <?php foreach ($_productCollection as $_product): ?>
				        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
				        <div class="product-item-info" data-container="product-grid">
				        	<div class="cdz-hover-section">
					        	<div class="cdz-product-top">
						            <?php
						            $productImage = $block->getImage($_product, $image);
						            $productHoverImage = $block->getImage($_product, $image_hover);
						            if ($pos != null) {
						                $position = ' style="left:' . $productImage->getWidth() . 'px;'
						                    . 'top:' . $productImage->getHeight() . 'px;"';
						            }
						            ?>
						            <?php // Product Image ?>
						            <?php if($block->isShow('thumb')): ?>
						            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
						                <span class="main-image">
											<?php echo $productImage->toHtml(); ?>
										</span>
										<span class="hover-image">
											<?php echo $productHoverImage->toHtml(); ?>
										</span>
						            </a>
						            <?php endif ?>
                                    <div class="cdz-product-wishlist">
										<?php if($block->isShow('addto')): ?>
                                        <div class="actions-secondary show-tooltip" data-role="add-to-links" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   class="action towishlist"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                        <?php endif ?>
                                    </div>
                                    
						            <div class="addto-hover-container">					            	
                                        <div class="addto-button">
                                            <?php echo $this->helper('Codazon\QuickShop\Helper\Data')->getQuickShopButton($_product) ?>
											
                                        </div>
			                    	</div>
			                    	<?php $labelHelper->showLabel($_product) ?>
									<div class="product-item-inner">
										<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
											<?php if($block->isShow('addtocart')): ?>
											<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey')?>
														<button type="submit"
																title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																class="action tocart primary">
															<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
											<?php endif ?>				                        
										</div>
									</div>
					        	</div>
				        	</div>
				            <div class="product details product-item-details">
                            	<div class="info-details">
									<?php
                                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <?php if($block->isShow('name')): ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                    <?php endif ?>
                                    <?php if($block->isShow('review')): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?php endif ?>
                                    <?php if($block->isShow('price')): ?>
                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                    <?php endif ?>
                                    <?php echo $swatchesRender->setProduct($_product)->setData('uniqid',$uniqId)->toHtml() ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>
                                    <?php if($block->isShow('description')): ?>
                                        <div class="product description product-item-description">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                               class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                
				                
				            </div>
				        </div>
				        <?php echo($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
				    <?php endforeach; ?>
				</div>
			</div>
			<?php echo $block->getToolbarHtml() ?>
			<?php if (!$block->isRedirectToCartEnabled()) : ?>
				<script type="text/x-magento-init">
				{
				    "[data-role=tocart-form], .form.map.checkout": {
				        "catalogAddToCart": {}
				    }
				}
				</script>
			<?php endif; ?>
            <?php if($_productCollection->getLastPageNumber() > 1): ?>
			<div class="ajax-load-wrapper">
				<div class="ajax-load-button">
					<a href="javascript:void(0)" class="btn cdz-ajax-trigger">
						<?php echo __('Load more') ?>
					</a>
					<div class="ajax-loader" style="display:none;"><?php echo __('Loading...') ?></div>
				</div>
			</div>
			<?php endif ?>
		</div>
	</div>
<?php endif; ?>
<script type="text/x-magento-init">
{
	"#<?php echo $uniqId ?>":{
		"Codazon_ProductFilter/js/ajaxload":{
			"ajaxUrl": "<?php echo $this->getUrl('productfilter/index/ajaxLoad') ?>",
			"currentUrl": "<?php echo $this->getUrl() ?>",
			"jsonData": <?php echo json_encode($block->getData()) ?>
		}
	}
}
</script>
<script type="text/javascript">
require(['jquery','Magento_Theme/js/fastest_fashion'],function($){
	var $_productWrap = $("#<?php echo $uniqId ?>");
	$_productWrap.sameHeightItems();
	$_productWrap.appearingEffect();
});
</script>