<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
//"swatchRenderer": {
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<?php $uniqId = uniqid('swatches-style01-'); ?>
<div class="swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId() ?>" id="<?php echo  $uniqId ?>"></div>
<script>
    require(["jquery", "jquery/ui", "Magento_Swatches/js/swatch-renderer"], function ($) {
		if(typeof $('#<?php echo  $uniqId ?>').data('swatch_renderer') == 'undefined'){
			$('#<?php echo  $uniqId ?>').data('swatch_renderer',true);
			$('#<?php echo  $uniqId ?>').SwatchRenderer({
				selectorProduct: '.product-item-details',
				onlySwatches: true,
				enableControlLabel: false,
				numberToShow: <?php /* @escapeNotVerified */ echo $block->getNumberSwatchesPerProduct(); ?>,
				jsonConfig: <?php /* @escapeNotVerified */ echo $block->getJsonConfig(); ?>,
				jsonSwatchConfig: <?php /* @escapeNotVerified */ echo $block->getJsonSwatchConfig(); ?>,
				mediaCallback: '<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>'
			});
		}
    });
</script>