<?php
/**
 * Copyright © 2017 Codazon. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<?php
$widget = ['Magento_Swatches/js/swatch-renderer' => [
    'selectorProduct'       => '.product-item-details',
    'onlySwatches'          => true,
    'enableControlLabel'    => false,
    'numberToShow'          => $block->getNumberSwatchesPerProduct(),
    'jsonConfig'            => json_decode($block->getJsonConfig()),
    'jsonSwatchConfig'      => json_decode($block->getJsonSwatchConfig()),
    'mediaCallback'         => $block->getMediaCallback()
]];
?>
<div class="swatch-opt-<?= $block->getProduct()->getId() ?> product-item-swatch" data-mage-init='<?= json_encode($widget) ?>'></div>