<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<div class="authorization-link switcher <?php echo $block->isLoggedIn() ? 'log-out' : 'log-in' ?>" id="authorization-top-link">
	<div class="actions dropdown options switcher-options">
		<div class="action toggle switcher-trigger" id="authorization-trigger">
			<?php echo __('Your account') ?>
		</div>
		<div style="display:none;" id="cdz-login-form-dropdown" class="cdz-login-form-dropdown dropdown switcher-dropdown">
			<?php echo $block->getChildHtml() ?>
		</div>
	</div>
</div>
<script type="text/javascript">
require(['jquery','dropdownDialog'],function($){
    var $dropdown = $('#cdz-login-form-dropdown');
    $dropdown.dropdownDialog({
        "appendTo":"#authorization-top-link > .options",
        "triggerTarget":"#authorization-trigger",
        "closeOnMouseLeave": false,
        "triggerClass":"active",
        "parentClass":"active",
        "buttons":null
    });
});
</script>