<?php
use Magento\Framework\App\Action\Action;
?>

<?php
$_productCollection = $block->getProductCollection();
?>
<?php if ($_productCollection->count()): ?>
    <?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $uniqId = uniqid('block_');
	$descLength = 100;
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $image_hover = 'category_page_grid_hover';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
	$gallery = $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Codazon_ProductFilter::vertical-gallery.phtml')
        ->setImageWidth($block->getData('thumb_width'))->setImageHeight($block->getData('thumb_height'));
?>

<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
<?php $iterator = 1; ?>
<?php foreach ($_productCollection as $_product): ?>
    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
    <div class="product-item-info" data-container="product-grid">
        <?php
        $productImage = $block->getImage($_product, $image);
        $productHoverImage = $block->getImage($_product, $image_hover);
        if ($pos != null) {
            $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"';
        }
        ?>
        <?php if($block->isShow('thumb')): ?>
        <div class="cdz-hover-section">
            <div class="cdz-product-top">
                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                    <?php echo $productImage->toHtml(); ?>
                </a>
                <?php echo $gallery->setProduct($_product)->toHtml(); ?>
            </div>
            <div class="cdz-product-wishlist">
                <?php if($block->isShow('addto')): ?>
                <div class="actions-secondary show-tooltip" data-role="add-to-links" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>">
                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                        <a href="#"
                           class="action towishlist"
                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                           data-action="add-to-wishlist"
                           role="button">
                           <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                        </a>
                    <?php endif; ?>
                </div>
                <?php endif ?>
            </div>
            <?php $labelHelper->showLabel($_product) ?>                                								
        </div>
        <?php endif ?>
        <div class="product details product-item-details">
            <div class="product-details-top">
                <?php echo $this->helper('Codazon\QuickShop\Helper\Data')->getQuickShopButton($_product,''); ?>
                <?php
                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                ?>
                <?php if($block->isShow('name')): ?>
                <strong class="product name product-item-name">
                    <a class="product-item-link"
                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                    </a>
                </strong>
                <?php endif ?> 
                <?php if($block->isShow('description')): ?>
                    <?php $desc = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                    if(strlen($desc)> $descLength ) { 
                        $strCutDesc = substr($desc, 0, $descLength);
                        $desc = substr($strCutDesc, 0, strrpos($strCutDesc, ' ')).'&hellip;';
                    }
                    $desc = $this->stripTags($desc,null,true);
?>
                    <div class="product description product-item-description">
                        <?php /* @escapeNotVerified */ echo $desc; ?>
                    </div>
                <?php endif; ?>
                <?php if($block->isShow('price')): ?>
                <?php echo $block->getProductPriceHtml($_product,'new-trend') ?>
                <?php endif ?>
                <?php echo $block->getProductDetailsHtml($_product); ?>
                <?php if($block->isShow('review')): ?>
                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                <?php endif ?>
            </div>
            <div class="cdz-product-bottom">
                <div class="cdz-buttons-container">
                    <div class="cdz-buttons-inner">											
                        <?php if($block->isShow('addtocart')): ?>
                            <?php if ($_product->isSaleable()): ?>
                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                            class="action tocart primary show-tooltip">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                    </button>
                            </form>
                            <?php endif ?>
                        <?php endif ?>
                        <?php
                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                        ?>
                        <a href="#"
                        class="action tocompare show-tooltip"
                        title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                        aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                        data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                        role="button">
                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
<?php endforeach; ?>

<?php endif; ?>
