<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed without_tab">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items">
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title active"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       href="javascript:void();"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <div class="content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
    <?php 
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Codazon_ThemeOptions/js/process-reviews": {
                    "productReviewUrl": "<?= $this->getUrl('review/product/listAjax').'id/'.$product->getId() ?>",
                    "reviewsTabSelector": "#reviews"
                }
            }
        }
    </script>
    <script type="text/javascript">
	require(['jquery'],function($){      
	    $(".reviews-actions > a.add").click(function(){
	    	$('html, body').animate({
		        scrollTop: $("#review-form").offset().top
		    }, 1000);
	    });
        $(".reviews-actions > a.view").click(function(){
            $('html, body').animate({
                scrollTop: $("#reviews").offset().top
            }, 1000);
        });
	});
	</script>
<?php endif; ?>
